version: '3'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - my-network
    volumes:
      - $HOME/mongo_test_app_docker_volume:/data/db
    command: mongod --quiet --logpath /dev/null

  app:
    build: .
    depends_on:
      - mongo
    networks:
      - my-network

networks:
  my-network:
    driver: bridge